#!/bin/bash

selfName=$0
tempFileName="./.tempStraceFile"

if [ -z "$1" ]
then
	echo -e " Wrong number of argument\n"\
		"Please, choose a command to analyze\n"\
		"Usage is: $selfName <command> <command arguments .. >"
	exit -1
fi

StraceArguments=( $* )

# It is often useful to interrupt process from keyboard
# We should contunue execution of script after strace returns
trap "echo 'Termination of strace via Ctrl-C or SIGINT'" SIGINT
IFS=$'\n' arr=( `strace -c ${StraceArguments[@]} 2>&1` )
trap -- SIGINT

elemNum=${#arr[@]}

for (( inc = 2; inc < elemNum - 2; inc++))
do
	echo "${arr[inc]}" | awk '{printf "%-20s %-10s\n", $NF, $4;}' 
done
